services:
  kubecamp.catalog:
    build:
      context: ../
      dockerfile: .docker/dev.Dockerfile
    tty: true
    restart: unless-stopped
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kubecamp_catalog
      - SPRING_DATASOURCE_USERNAME=kubecamp
      - SPRING_DATASOURCE_PASSWORD=kubecamp
      - SPRING_JPA_HIBERNATE_JDBC_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    volumes:
      - ../:/app
    depends_on:
      - db
  db:
    image: postgres:14.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=kubecamp
      - POSTGRES_PASSWORD=kubecamp
      - POSTGRES_DB=kubecamp_catalog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
